export const CREATOR_SELECTION = {
  START_TRIP: "START_TRIP",
  MANAGE_HISTORY: "MANAGE_HISTORY",
};

export const ROUTE = {
  HOMEPAGE: "HOMEPAGE",
  DIR_CONTAINER: "DIR_CONTAINER",
  NODE_CREATE_FORM: "NODE_CREATE_FORM",
  COMPASS: "COMPASS",
  PREVIEW_TRIP: "PREVIEW_TRIP",
};

export const NODE_TYPE = {
  SHOP: "SHOP",
  CHECKPOINT: "CHECKPOINT",
};

export const SUB_NODE_TYPE = {
  SHOP: {},
  CHECKPOINT: {},
};
