export const CREATOR_SELECTION = {
  START_TRIP: "START_TRIP",
  MANAGE_HISTORY: "MANAGE_HISTORY",
};

export const ROUTE = {
  HOMEPAGE: "HOMEPAGE",
  DIR_CONTAINER: "DIR_CONTAINER",
  NODE_CREATE_FORM: "NODE_CREATE_FORM",
  COMPASS: "COMPASS",
  PREVIEW_TRIP: "PREVIEW_TRIP",
  MARKET_SELECTION: "MARKET_SELECTION",
};

export const NODE_TYPE = {
  SHOP: "shop",
  CHECKPOINT: "checkpoint",
  FLOOR_CHANGE: "floor_change",
  GATE: "gate",
};

export const SUB_NODE_TYPE = {
  SHOP: {},
  CHECKPOINT: {},
};
